### ISSUE TITLE
Checklist for maturity

### ISSUE THREAD

**Issue by elliottower** [Farama-Foundation/Minari#76]
# Checklist for Maturity

- [ ] Fully deterministic 
  - As far as possible
- [ ] Explicit Versioning 
- [ ] Farama Notifications
- [ ] PyPI
- [ ] Full Package Description 
- [ ] Deploy via GH Actions 
- [ ] Website
- [ ] Linux and MacOS 
- [ ] Precommit 
- [ ] Typehinting 
- [ ] Docstrings 
- [ ] CI Testing 
- [ ] Logo 
- [ ] CoC 
- [ ] Gymnasium/PZ API 
- [ ] Python Versions 
  - >3.7
- [ ] JKTerry and Mark as owners 
- [ ] TOTP 
- [ ] Google Analytics 
- [ ] License 
- [ ] Donations
